### ISSUE TITLE
Provide invites to easily push meetings into calender

### ISSUE THREAD

**Issue by dipanm** [integra-consultores/meetings#5]
Provide the invite type message that allows the meetings that can be quickly added to calender. This would be very helpful for managing meeting-appointments.

**Comment by dipanm** [comment]
I will be working on this - I have found that by sending attachment based on iCalender (http://www.ietf.org/rfc/rfc2445.txt) along with the regular message will prompt the email client to add link to push the meeting to calender.

**Comment by dipanm** [comment]
![screen-shot-meeting](https://f.cloud.github.com/assets/4157091/465048/4bcd97ac-b621-11e2-9425-a8de5db5c443.png)

Take a look at the screen shot how meeting can now be handled in the gmail. Similar functionality will be available in outlook etc. but not really tested by me yet!

**Comment by dipanm** [comment]
Is this issue closed? or do we need to add more work to this?

**Comment by bishma-stornelli** [comment]
I forgot to close it.
