### ISSUE TITLE
Provide mails on updates apart from the create

### ISSUE THREAD

**Issue by dipanm** [integra-consultores/meetings#6]
When the meetings get updated, specially when the time changes, there should be additional notification (mail) for the meetings.

**Comment by dipanm** [comment]
I am planning to implement this now. I need your advise, @bishma-stornelli. 

Should there be two functions like `meeting_add` and `meeting_update` in the mailer patch? or should there be single    function (e.g. `meeting_notify`)  as majority of the code is similar between the two. ?

**Comment by bishma-stornelli** [comment]
Take a look at the Mailer class. I think there is a method issue_add and
issue_update. It's handled differently. You could do the same or try to
have only one method. If you're repeating too much code maybe you could
take the common code to another method or if it's very easy you could
handle it in one method and use if - else to make the differences. Whatever
you find easier.

2013/5/28 Dipan notifications@github.com

**Comment by dipanm** [comment]
Please take a look at #10 which solves this issue thoroughly. My check-in notes explains all scenarios and I have tested this thoroughly. 

It now has single meeting_save() handler which provides mail for both the types of notifications (new & updates) and includes information from journal. This is both necessary and cleans up the code because there is no duplication of code.

Please have a look and let me know if anything more is needed. If all looks good, please accept the code.
