### ISSUE TITLE
Plugin breaks when rendering of meetings having attachments results in Internal Errors

### ISSUE THREAD

**Issue by dipanm** [integra-consultores/meetings#8]
When you attach a file with a meeting and update the rendering fails with Internal error
<code>
Completed 500 Internal Server Error in 56ms
ActionView::Template::Error (wrong number of arguments (1 for 0)):
    75:           </div>
    76:         </div>
    77:         <% end %>
    78:         <%= link_to_attachments @meeting, :thumbnails => true %>
    79:         <% end -%>
    80: </div>
    81: 
  lib/plugins/acts_as_attachable/lib/acts_as_attachable.rb:51:in `attachments_deletable?'
  app/helpers/attachments_helper.rb:29:in`link_to_attachments'
</code>

The configuration is: 

**Environment:**
  Redmine version                          2.2.3.stable
  Ruby version                             1.9.3 (i686-linux)
  Rails version                            3.2.12
  Environment                              production
  Database adapter                         Mysql2

This was tested on the head as of today.

**Comment by dipanm** [comment]
I have seen this working sometime long back - so I wanted to debug whether this bug has been caught on during any latest check-ins.

I can confirm you that on the same system - same database, the check in which reproduces the problem is: 
https://github.com/integra-consultores/meetings/commit/ee37d385a47452d26de4306e5a2e478cff7c5f51
- **Added filter by meeting in time entries' details.**
  All above checkins till head also has the problem. 

Further, I can confirm that the check in doesn't reproduce problem is the one below it: 
https://github.com/integra-consultores/meetings/commit/4997a11e5343fa6b2bdc682a281fbf31cc54bc0e
- **Only show meetings of projects with module meetings enabled.**

So that specific check-in has introduced the issue. 

I have also verified that size of the attachment, mimetype of attachement makes no difference.

**Comment by dipanm** [comment]
I think from what I understood - the method `link_to_attachments` calls `attachments_deletable?` method.

This method in turn calls `visible?(user)` - which must have 1 argument - however the method `def visible?`  in `meetings.rb` - takes no argument. 

This method actually was introduced in the patch - https://github.com/integra-consultores/meetings/commit/ee37d385a47452d26de4306e5a2e478cff7c5f51.  Hence, the error was pretty much introduced in this patch. 

What I am wondering is how was this whole thing working before?

**Comment by bishma-stornelli** [comment]
Thanks for your work @dipanm .

The reason it was working before that patch is because the method attachments_deletable? is defined as:

```
        def attachments_deletable?(user=User.current)
          (respond_to?(:visible?) ? visible?(user) : true) &&
            user.allowed_to?(self.class.attachable_options[:delete_permission], self.project)
        end
```

and as you can see, it asks if the attachable (in this case the meeting) responds to the method `:visible?`. Since this patch introduced that method, now it is being called but it only receives 0 arguments. I'll commit a solution for that.
