### ISSUE TITLE
How to "Apply patches in plugins/meetings/patches"?

### ISSUE THREAD

**Issue by huangxh16888** [integra-consultores/meetings#9]
I'm new in ruby,I don't know how to "Apply patches in plugins/meetings/patches".Could somebody tell me?Thanks.

**Comment by bishma-stornelli** [comment]
Check [redmine documentation](http://www.redmine.org/projects/redmine/wiki/Patch). I know this work for linux, not sure if this work for windows.

Basically you run:

```
patch -p0 < path_to_patch.diff
```

You can check if there is any error before applying the path by running it with the `--dry-run` flag:

```
patch -p0 --dry-run < path_to_patch.diff
```

If you don't see any error, it's safe to patch.
